server:
  port: 7700

spring:
  application:
    name: eureka-consumer-feign-custom

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 设置心跳检测频率和超时时间
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

# Feign logging
logging:
  level:
    jj.fly.spring.cloud.demo.feign.client.UserFeignClient: DEBUG