server:
  port: 7900

spring:
  application:
    name: eureka-provider
    #name: eureka-provider-v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: my-zone # eureka可以理解的元数据
      #不会影响客户端行为
      mydata: my data
    # 设置心跳检测频率和超时时间
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5