server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: demo-sidecar

sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json


security:
  basic:
    enabled: true
  user:
    name: user
    password: password
