
server:
  port: 8762

spring:
  application:
    name: eureka-ha
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 设置心跳检测频率和超时时间
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://user:password@peer1:8761/eureka/
  server:
    enable-self-preservation: true # 关闭自我保护机制
  dashboard:
    enabled: false

security:
  basic:
    enabled: true
  user:
    name: user
    password: password