server:
  port: 7800

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 设置心跳检测频率和超时时间
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

user:
  service:
    path: http://localhost:7900/test/findById/